### ISSUE TITLE
Form Persönliche Angaben: Special characters "Geburtsort", "Vorname", "Nachname"

### ISSUE THREAD

**Issue by Aragorn71** [epha/www#20]
Spaces have to be accepted in field Geburtsort i.e. "Hausen am Albis"

**Comment by ephaee** [comment]
This affects first and lastname too (see #17) 

https://regex101.com/r/yM2lS3/2

- L'Abbaye (VD)
- Aïre (GE)
- Aire-la-Ville (GE)
- Alt St. Johann (SG)
- Neuchâtel (NE)
- Choëx (VS)
- Carì (TI)
- Le Chalet-à-Gobet (VD)
- Le Crêt-près-Semsales (FR)

- Marie-Hélène
