### ISSUE TITLE
Persönliche Angaben: field "Geburtstag" not all years should be accepted

### ISSUE THREAD

**Issue by Aragorn71** [epha/www#24]
i.e. 1756 is accepted as a birthdate, this should not be possible. Please limit to a maximum age of 130 years and no dates in the future should be accepted.

**Comment by ephaee** [comment]
Jonas set 1890-01-01 as minimum date https://github.com/epha/www/commit/f8d11cb52ab78eb6c57421303e1e6618c5a81d0f#diff-63dee5f81a79c7d4d1adf399cd22e381R134

and maximum date as of today
https://github.com/epha/www/commit/f8d11cb52ab78eb6c57421303e1e6618c5a81d0f#diff-63dee5f81a79c7d4d1adf399cd22e381R438
